apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
spec:
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image: gcr.io/useful-cathode-334010/adservice:latest
          ports:
            - containerPort: 9555
          env:
            - name: PORT
              value: "9555"
            # Lightstep config
            - name: LS_SERVICE_NAME
              value: "adservice"
            - name: LS_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: lightstep-credentials
                  key: accessToken
            - name: OTEL_LOG_LEVEL
              value: "error"
          resources:
            requests:
              cpu: 200m
              memory: 180Mi
            limits:
              cpu: 300m
              memory: 300Mi
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 60
            exec:
              command:
                [
                  "/bin/grpc_health_probe",
                  "-addr=:9555",
                  "-connect-timeout=60s",
                  "-rpc-timeout=60s",
                ]
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 60
            exec:
              command:
                [
                  "/bin/grpc_health_probe",
                  "-addr=:9555",
                  "-connect-timeout=60s",
                  "-rpc-timeout=60s",
                ]
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
spec:
  type: ClusterIP
  selector:
    app: adservice
  ports:
    - name: grpc
      port: 9555
      targetPort: 9555
